FILESEXTRAPATHS_prepend := "${THISDIR}/files:"

SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/.settings/language.settings.xml"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/STM32MP157AACX_RAM.ld"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/.project"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/lte_sensors_CM4_Debug.launch"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/RemoteProc/README"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/RemoteProc/fw_cortex_m4.sh"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/lte_sensors_CM4_Debug.cfg"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/lock_resource.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/syscalls.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/sysmem.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/stm32mp1xx_it.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/rsc_table.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/mbox_ipcc.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/openamp.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/main.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/stm32mp1xx_hal_msp.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Src/openamp_log.c"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Startup/startup_stm32mp157aacx.s"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/mbox_ipcc.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/stm32mp1xx_it.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/stm32mp1xx_hal_conf.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/openamp.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/main.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/rsc_table.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/lock_resource.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/openamp_log.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/Inc/openamp_conf.h"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/VL53L0X/single_shot.cpp"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/VL53L0X/VL53L0X.cpp"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/VL53L0X/I2Cdev.cpp"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/VL53L0X/VL53L0X_defines.hpp"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/VL53L0X/I2Cdev.hpp"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/Core/VL53L0X/VL53L0X.hpp"
SRC_URI += "file://Projects/Avenger96/lte_sensors/CM4/.cproject"

do_patch_append() {
    import shutil
    shutil.copytree(d.getVar('WORKDIR') + "/Projects/Avenger96", d.getVar('S') + "/Projects/Avenger96")
}

